POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test Title",
    "author": "Test Author",
    "url": "http://testurl.com/",
    "likes": 123,
    "userId": "5e9641ae9ce1622dc45ceda2"
}